pull_request_rules:
  - name: backport patches to the release branch and assign to original author
    conditions:
      - label = backport
    actions:
      backport:
        branches:
          - "version-15"
        assignees:
          - "{{ author }}"